### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by amotl**
Dear Henri,

thanks for integrating #4. This patch adds some improvements to the documentation and, through bf980d27, some convenience for users to invoke the program instead of having to address the `.jar` file.

With kind regards,
Andreas.

### CODE REVIEW

**Comment by hgomez** [comment]
I won't use this URL in setup https://raw.githubusercontent.com/daq-tools/influxdb-fetcher/develop/bin/influxdb-fetcher section

**Comment by amotl** [comment]
> I won't use this URL in setup.

True, thanks! Can you tag your repository with `1.0.1` and then add the build `influxdb-fetcher-1.0.1.jar` as an artifact/asset to the GitHub release - similar to what I did at [1]? Then, I can amend this patch accordingly.

[1] https://github.com/daq-tools/influxdb-fetcher/releases

**Comment by amotl** [comment]
Maybe also rename the repository itself to `influxdb-fetcher`? No worries about the "Cool URIs don't change" thing. GitHub will automatically redirect people accessing the repository to the new location - both on the Web side as well as the Git side of things.

**Comment by hgomez** [comment]
I released 1.0.2, and included jar
Let's keep influxdb as repository name, more tools may surface later

**Comment by amotl** [comment]
> I released 1.0.2, and included jar.

Thanks.

> Let's keep `influxdb` as repository name, more tools may surface later.

All right.

I've just amended this patch to make the URLs match your repository layout again.

**Comment by hgomez** [comment]
Thanks Andreas

**Comment by amotl** [comment]
Thank you as well, Henri. I verified that the installation procedure works and then added a comment at https://github.com/influxdata/influxdb/issues/3904#issuecomment-771031435 in order to reflect the recent improvements.

**Pull request merged**
